import { type NextPage } from "next";
import Head from "next/head";
import Keys from "../components/keys";

const Home: NextPage = () => {
  const targetKeys = ["control", "shift", "p"];
  const targetCombination = targetKeys.join("+");
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <Keys targetKeys={targetKeys} targetCombination={targetCombination} />
      </main>
    </>
  );
};

export default Home;
